# -*- coding: utf-8 -*-
"""Fake News Text Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StBzxB7NNUzMJwfMx7qXTdlI12WmU8Kw
"""

!pip install fastapi uvicorn nest-asyncio trafilatura transformers torch requests

!pip install transformers torch trafilatura

import trafilatura
from transformers import pipeline
import textwrap
import requests

class FakeNewsEngine:
    def __init__(self):
        print("🤖 Initializing Fake News Transformer Engine...")
        self.classifier = pipeline("text-classification", model="winterForestStump/Roberta-fake-news-detector")
        print("✅ Model loaded successfully!\n")

    def scrape_text(self, url):
        """Extracts text using a disguised browser request."""
        print(f"🌐 Scraping article from: {url}")

        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
        }

        try:
            # 1. Fetch the HTML pretending to be a real human browser
            response = requests.get(url, headers=headers, timeout=10)

            # 2. Check if the site still blocked us
            if response.status_code != 200:
                print(f"⚠️ Warning: Site returned status code {response.status_code}")
                return None

            # 3. Extract the clean text from the downloaded HTML
            text = trafilatura.extract(response.text)
            return text

        except Exception as e:
            print(f"⚠️ Request failed: {e}")
            return None

    def analyze_article(self, url):
        """Scrapes the URL and runs the text through the Transformer model."""
        article_text = self.scrape_text(url)

        if not article_text:
            return {"error": "Could not extract text. The site has strict anti-bot firewalls."}

        # Transformers have a token limit. We grab the first 2000 chars.
        truncated_text = article_text[:2000]

        print("🧠 Analyzing linguistic patterns and semantics...")
        result = self.classifier(truncated_text)[0]

        label = result['label']
        confidence = round(result['score'] * 100, 2)

        return {
            "status": "success",
            "prediction": label,
            "confidence": confidence,
            "preview_text": textwrap.shorten(article_text, width=150, placeholder="...")
        }

if __name__ == "__main__":
    engine = FakeNewsEngine()
    test_urls = ["https://www.theonion.com/man-just-buying-one-of-every-cleaning-product-in-case-1819576081",
        "https://en.wikipedia.org/wiki/Transformer_(deep_learning_architecture)"]

    for url in test_urls:
        print("-" * 60)
        report = engine.analyze_article(url)

        if "error" in report:
            print(f"❌ Error: {report['error']}")
        else:
            print("\n📊 --- ANALYSIS REPORT ---")
            print(f"Snippet: {report['preview_text']}")

            if report['prediction'] == 'FAKE':
                print(f"Verdict: 🔴 FAKE/UNRELIABLE ({report['confidence']}% confidence)")
            else:
                print(f"Verdict: 🟢 REAL NEWS ({report['confidence']}% confidence)")
        print("-" * 60 + "\n")

import trafilatura
from transformers import pipeline
import textwrap
import requests
import re

class FakeNewsEngine:
    def __init__(self):
        print("🤖 Initializing Fake News Transformer Engine...")
        self.classifier = pipeline("text-classification", model="winterForestStump/Roberta-fake-news-detector")
        print("✅ Model loaded successfully!\n")

    def scrape_text(self, url):
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        }
        try:
            response = requests.get(url, headers=headers, timeout=10)
            if response.status_code != 200:
                return None
            return trafilatura.extract(response.text)
        except Exception:
            return None

    def fact_check_claim(self, keyword_query):
        """Searches Wikipedia API for debunked claims, using a browser disguise."""
        print(f"🔎 Cross-referencing databases for: '{keyword_query}'...")


        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36"
        }

        try:
            wiki_url = f"https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch={keyword_query} debunked OR hoax OR conspiracy&utf8=&format=json"
            response = requests.get(wiki_url, headers=headers, timeout=10)

            # Make sure we got a successful 200 OK response
            if response.status_code == 200:
                wiki_res = response.json()

                if wiki_res['query']['search']:
                    evidence = []
                    for res in wiki_res['query']['search'][:2]: # Get top 2 results
                        # Clean the Wikipedia HTML snippet using regex
                        clean_snippet = re.sub(r'<[^>]+>', '', res['snippet'])
                        evidence.append(f"- Source: {res['title']} | Context: {clean_snippet[:120]}...")
                    return "\n".join(evidence)
        except Exception as e:
            return f"Fact-check search failed: {e}"

        return "No fact-check records found. Proceed with caution."

    def analyze_article(self, url, search_claim):
        """Runs the AI model AND the Fact Checker."""
        article_text = self.scrape_text(url)

        if not article_text:
            return {"error": "Could not extract text. Site might be blocking scrapers or link is dead."}

        # 1. AI Linguistic Analysis
        truncated_text = article_text[:2000]
        print("🧠 Analyzing linguistic patterns...")
        result = self.classifier(truncated_text)[0]

        # 2. Fact Check Cross-Reference
        fact_check_results = self.fact_check_claim(search_claim)

        return {
            "prediction": result['label'],
            "confidence": round(result['score'] * 100, 2),
            "preview_text": textwrap.shorten(article_text, width=150, placeholder="..."),
            "fact_check": fact_check_results
        }


if __name__ == "__main__":
    engine = FakeNewsEngine()

    test_cases = [
        {
            "url": "https://en.wikipedia.org/wiki/Moon_landing_conspiracy_theories",
            "claim": "Moon landing was faked"
        }
    ]

    for test in test_cases:
        print("-" * 80)
        print(f"🌐 Target: {test['url']}")
        report = engine.analyze_article(test['url'], test['claim'])

        if "error" in report:
            print(f"❌ Error: {report['error']}")
        else:
            print("\n📊 --- FINAL MULTI-MODAL REPORT ---")
            print(f"Snippet: {report['preview_text']}\n")

            if report['prediction'] == 'FAKE':
                print(f"🤖 AI Verdict: 🔴 LIKELY FAKE/UNRELIABLE ({report['confidence']}% confidence)")
            else:
                print(f"🤖 AI Verdict: 🟢 LIKELY REAL/FACTUAL ({report['confidence']}% confidence)")

            print(f"\n📚 FACT-CHECK EVIDENCE:\n{report['fact_check']}")
        print("-" * 80 + "\n")

import nest_asyncio
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from transformers import pipeline
import textwrap
import requests
import trafilatura
import threading
import time
from fastapi.middleware.cors import CORSMiddleware
from google.colab import output

# 1. Initialize the Web Server
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
)

# 2. Loading the AI Model
print("🤖 Initializing AI Model (Please wait)...")
classifier = pipeline("text-classification", model="winterForestStump/Roberta-fake-news-detector")
print("✅ AI Model Loaded!")

class AnalyzeRequest(BaseModel):
    url: str = ""
    text: str = ""

def fetch_wikipedia_evidence(claim):
    """Searches Wikipedia API for historical or factual context matching the claim."""
    search_url = "https://en.wikipedia.org/w/api.php"
    params = {
        "action": "opensearch",
        "search": claim,
        "limit": 2,
        "namespace": 0,
        "format": "json"
    }
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    try:
        res = requests.get(search_url, params=params, headers=headers, timeout=5).json()
        titles = res[1]
        snippets = res[2]

        evidence_list = []
        for i in range(len(titles)):
            evidence_list.append(f"Source: {titles[i]} | Context: {snippets[i]}")
        return evidence_list if evidence_list else ["No explicit fact-check matches found on Wikipedia."]
    except Exception as e:
        return [f"Fact-check search bypassed: {str(e)}"]

@app.post("/analyze")
def analyze_article(req: AnalyzeRequest):
    content = ""
    source_used = ""


    if req.text.strip() and len(req.text.strip()) > 100:
        content = req.text
        source_used = "Extension Screen Capture"

    elif req.url.strip():
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36"}
        try:
            response = requests.get(req.url, headers=headers, timeout=10)
            if response.status_code == 200:
                content = trafilatura.extract(response.text)
        except:
            pass
        source_used = "URL Web Scraper"

    if not content:
        # If both fail or text was too short, use a default fallback to keep it from crashing
        content = req.text if req.text.strip() else "Unknown source text."
        source_used = "Fallback Context Input"

    # 4. Process Text with AI
    result = classifier(content, truncation=True, max_length=512)[0]

    # 5. Extract a quick claim headline for the Fact-Checker
    title_claim = content.split('\n')[0][:60] if content else "News updates"
    evidence = fetch_wikipedia_evidence(title_claim)

    return {
        "status": "success",
        "source_method": source_used,
        "verdict": result["label"],
        "confidence": round(result["score"] * 100, 2),
        "snippet": textwrap.shorten(content, width=120, placeholder="..."),
        "fact_check": evidence
    }

nest_asyncio.apply()
def run_server():
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="warning")

server_thread = threading.Thread(target=run_server, daemon=True)
server_thread.start()
time.sleep(2)
print("\n🔌 Establishing secure Localtunnel bridge...")
import urllib


ip = urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n")
print(f"\n🔐 SECURITY PASSWORD (Copy this IP): {ip}\n")

# Start localtunnel
!npm install -g localtunnel > /dev/null 2>&1
!lt --port 8000